<a href="https://colab.research.google.com/github/gasotoga/Phyton/blob/main/UseDrugsData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importar librerias panda matlib y las de gráficos
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# cargar el archivo excel /content/1.4_-_Prevalence_of_drug_use_in_the_youth_population_national_data_including_NPS.xlsx
df = pd.read_excel('/content/1.4_-_Prevalence_of_drug_use_in_the_youth_population_national_data_including_NPS.xlsx')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604 entries, 0 to 603
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CANNABIS USE  10 non-null     object
 1   Unnamed: 1    21 non-null     object
 2   Unnamed: 2    600 non-null    object
 3   Unnamed: 3    600 non-null    object
 4   Unnamed: 4    521 non-null    object
 5   Unnamed: 5    446 non-null    object
 6   Unnamed: 6    413 non-null    object
 7   Unnamed: 7    600 non-null    object
 8   Unnamed: 8    597 non-null    object
 9   Unnamed: 9    235 non-null    object
dtypes: object(10)
memory usage: 47.3+ KB

In [14]:
# cargar el archivo excel con todas las hojas en el mismo df
df = pd.read_excel('/content/1.4_-_Prevalence_of_drug_use_in_the_youth_population_national_data_including_NPS.xlsx',
                   sheet_name=None)

In [15]:
#concatenar todo el contenido en un único df
df = pd.concat(df.values())

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4183 entries, 0 to 215
Data columns (total 26 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   CANNABIS USE                       10 non-null     object
 1   Unnamed: 1                         540 non-null    object
 2   Unnamed: 2                         3937 non-null   object
 3   Unnamed: 3                         3138 non-null   object
 4   Unnamed: 4                         3669 non-null   object
 5   Unnamed: 5                         2994 non-null   object
 6   Unnamed: 6                         2445 non-null   object
 7   Unnamed: 7                         3445 non-null   object
 8   Unnamed: 8                         3728 non-null   object
 9   Unnamed: 9                         2863 non-null   object
 10  OPIOIDS USE                        12 non-null     object
 11  COCAINE USE                        10 non-null     object
 12  Unnamed: 10                        539 non-null    object
 13  AMPHETAMINES USE                   11 non-null     object
 14  "Ecstasy"-type substances USE      10 non-null     object
 15  TRANQUILLIZERS and SEDATIVES USE   9 non-null      object
 16  New psychoactive substances (NPS)  7 non-null      object
 17  Unnamed: 11                        170 non-null    object
 18  Unnamed: 12                        170 non-null    object
 19  Unnamed: 13                        109 non-null    object
 20  Unnamed: 14                        64 non-null     object
 21  Unnamed: 15                        67 non-null     object
 22  Unnamed: 16                        439 non-null    object
 23  Country                            216 non-null    object
 24  Region                             216 non-null    object
 25  Subregion                          216 non-null    object
dtypes: object(26)
memory usage: 882.4+ KB

In [20]:
# mostrar el contenido del df para los primeros 200 registros
df.head(200)

,CANNABIS USE,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,New psychoactive substances (NPS),Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Country,Region,Subregion
0,among the youth population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Prevalence (percentage),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Region,Subregion,Country/ Territory,Coverage (age/grade),Lifetime,Past Year,Past Month,Year of Estimate,Source,Notes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFRICA,East Africa,Ethiopia,Youth (undefined),11,NaN,NaN,1999,ARQ,Ages not specified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Kenya,(HHS) age 15 - 17,1.1,NaN,0.9,2007,Govt.,Resin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,Colombia,University,31.16,15.01,7.14,2012,ARQ,Herb,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,Colombia,University,36.31,20.77,9.74,2016,Government,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,Colombia,15 - 16,14.18,9.65,5.01,2016,ARQ,Herb,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,Ecuador,12 - 17,6.4,4.2,2.2,2008,ARQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,Ecuador,University,11.41,4.43,1.68,2009,ARQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# descripción estadística básica del df
df.describe()

In [22]:
# descripción de todas las columnas df con su tipo de datos
df.dtypes

CANNABIS USE                         object
Unnamed: 1                           object
Unnamed: 2                           object
Unnamed: 3                           object
Unnamed: 4                           object
Unnamed: 5                           object
Unnamed: 6                           object
Unnamed: 7                           object
Unnamed: 8                           object
Unnamed: 9                           object
OPIOIDS USE                          object
COCAINE USE                          object
Unnamed: 10                          object
AMPHETAMINES USE                     object
"Ecstasy"-type substances USE        object
TRANQUILLIZERS and SEDATIVES USE     object
New psychoactive substances (NPS)    object
Unnamed: 11                          object
Unnamed: 12                          object
Unnamed: 13                          object
Unnamed: 14                          object
Unnamed: 15                          object
Unnamed: 16                          object
Country                              object
Region                               object
Subregion                            object
dtype: object